starting_height = float(input())
first_bounce_height = float(input())
num_bounces = int(input())
total_distance = starting_height + (2 * first_bounce_height * (first_bounce_height / starting_height)**num_bounces - 1)
print(total_distance)