def fix_spaces(text):
    text = text.replace(" ", "_")
    return (
        text.replace("  ", "_")
        .replace("___", "-___")
        .replace("----", "-")
        .replace("---", "-")
        .replace("--", "-")
        .replace("-", "-")
        .replace("_ _", "_")
        .replace("_ ___", "_-")
        .replace("_ ----", "_-")
        .replace("_ ---", "_-")
        .replace("_ --", "_-")
        .replace("_ -", "_-")
        .replace("_ ", "_")
    )