n = int(input())
prices, discounts = zip(*[list(map(float, input().split())) for _ in range(n)])
prices_discounts = list(zip(prices, map(int, discounts)))
total_price = sum(price * (1 - discount / 100.0) for price, discount in prices_discounts)
print(format(total_price, ".2f"))