n=int(input())
prices=map(float,input().split())
discounts=map(float,input().split())
total_price=sum(price*(1-(discount/100))for price,discount in zip(prices,discounts))
total_price=round(total_price,2)
print(total_price)